
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1000
  end

  config.vm.define "wordpress" do |wdpress|
    wdpress.vm.network "private_network", ip:"192.168.56.20"
  end

end
